[package]
name = "meshoui-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blue_engine = "0.5.9"
rapier3d = "0.18.0"
